name: Deploy to Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Container
      env:
        SECRET_PORT: ${{ secrets.SECRET_PORT }}
        SECRET_PRIVATE_SSH: ${{ secrets.SECRET_PRIVATE_SSH }}
        SECRET_SERVER: ${{ secrets.SECRET_SERVER }}
      run: |
        ssh -i $SECRET_PRIVATE_SSH -p $SECRET_PORT $SECRET_SERVER "cd /project/Swissdle 
        && git pull origin main 
        && cd backend-laravel && composer install
        && cd ../frontend-vue && npm install && npm run build"