name: Deploy to Container

on:
  push:
    branches:
      - 13_continuous_integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Container
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/known_hosts
        touch ~/.ssh/pkey
        echo "${{ secrets.SECRET_PUB }}" >> ~/.ssh/known_hosts
        echo "${{ secrets.SECRET_PRIVATE_SSH }}" > ~/.ssh/pkey
        chmod 600 ~/.ssh/pkey
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/pkey
        ssh ${{ secrets.SECRET_USER }}@${{ secrets.SECRET_HOST }} -p ${{ secrets.SECRET_PORT }} -i ~/.ssh/pkey "touch test.test"