name: Deploy to Container

on:
  push:
    branches:
      - 13_continuous_integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Container
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/known_hosts
        echo ${{ secrets.SECRET_PUB }} >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ${{ secrets.SECRET_PRIVATE_SSH }}