name: Deploy to Container

on:
  push:
    branches:
      - 13_continuous_integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Container
      env:
        SECRET_PORT: ${{ secrets.SECRET_PORT }}
        SECRET_PRIVATE_SSH: ${{ secrets.SECRET_PRIVATE_SSH }}        
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.SECRET_HOST }} >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ${{ secrets.SECRET_PRIVATE_SSH }}
        ssh -i -p ${{ secrets.SECRET_PORT }} ${{ secrets.SECRET_USER }}@${{ secrets.SECRET_HOST }} "cd /project/Swissdle 
        && git pull origin main 
        && cd backend-laravel && composer install
        && cd ../frontend-vue && npm install && npm run build"